---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-microservices-config
data:
  PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-microservices
  labels:
    app: istio-microservices
spec:
  replicas: 3
  selector:
    matchLabels:
      app: istio-microservices
  template:
    metadata:
      labels:
        app: istio-microservices
    spec:
      containers:
      - name: istio-microservices
        image: jignyasamishra/istio-microservices:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: istio-microservices-config
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: istio-microservices
spec:
  selector:
    app: istio-microservices
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: istio-microservices-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-microservices
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50